name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write  # Necesario para CodeQL y Dependency Review

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      security-events: write  # Permiso necesario para subir resultados
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read  # Permiso necesario para eventos pull_request
    if: ${{ github.event_name == 'pull_request' }}  # Ejecutar solo en pull_request
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}