
name: ATLANTYDE SemVer Check

on:
  workflow_dispatch:

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - name: Validar marcas de versión
        run: |
          echo "🔍 Verificando marcas SemVer en el repositorio..."
          grep -rE 'ATLANTYDE v[0-9]+\.[0-9]+\.[0-9]+' . || echo "::notice::No se detectaron marcas de versión en algunos archivos."
